// Utility functions for quick actions across portals
// These will later be replaced with actual API calls

import jsPDF from 'jspdf';

export const showNotification = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
  // Console log for debugging
  console.log(`[${type.toUpperCase()}] ${message}`);

  // Create a visible notification element
  const notification = document.createElement('div');
  notification.className = `fixed top-4 right-4 z-50 p-4 rounded-lg shadow-lg max-w-md ${type === 'success' ? 'bg-green-600 text-white' :
      type === 'error' ? 'bg-red-600 text-white' :
        'bg-blue-600 text-white'
    }`;
  notification.innerHTML = `
    <div class="flex items-center">
      <span class="mr-2">${type === 'success' ? '✅' : type === 'error' ? '❌' : 'ℹ️'}</span>
      <span>${message}</span>
    </div>
  `;

  document.body.appendChild(notification);

  // Remove notification after 4 seconds
  setTimeout(() => {
    if (notification.parentNode) {
      notification.parentNode.removeChild(notification);
    }
  }, 4000);
};

export const generateReport = (reportType: string, format: string = 'PDF') => {
  const timestamp = new Date().toLocaleString();
  const fileName = `${reportType.replace(/\s+/g, '_')}_${new Date().getTime()}`;

  try {
    if (format === 'PDF') {
      // Generate PDF
      const doc = new jsPDF();

      // Add title
      doc.setFontSize(20);
      doc.text(reportType, 20, 20);

      // Add metadata
      doc.setFontSize(12);
      doc.text(`Generated: ${timestamp}`, 20, 35);
      doc.text(`Report Type: ${reportType}`, 20, 45);

      // Add content section
      doc.setFontSize(14);
      doc.text('Report Summary', 20, 60);

      doc.setFontSize(10);
      const reportContent = [
        'This is a generated report from the Agricultural Finance Coordination Framework.',
        '',
        'Key Metrics:',
        '• Total Applications: 156',
        '• Approved: 128',
        '• Pending: 20',
        '• Rejected: 8',
        '',
        'Financial Overview:',
        '• Total Disbursed: ₦2,450,000,000',
        '• Recovery Rate: 87%',
        '• Active Loans: 342',
        '',
        'Regional Distribution:',
        '• North Central: 45 applications',
        '• North East: 38 applications',
        '• North West: 52 applications',
        '• South East: 42 applications',
        '• South South: 48 applications',
        '• South West: 55 applications',
        '',
        'This report was automatically generated by the AFCF system.',
        `Generated on: ${timestamp}`,
      ];

      let yPosition = 70;
      reportContent.forEach(line => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, 20, yPosition);
        yPosition += 7;
      });

      // Save PDF
      doc.save(`${fileName}.pdf`);
      showNotification(`${reportType} downloaded successfully as PDF!`, 'success');

    } else if (format === 'Excel' || format === 'CSV') {
      // Generate CSV data (Excel will open CSV files)
      const csvContent = [
        ['Agricultural Finance Coordination Framework'],
        [`Report: ${reportType}`],
        [`Generated: ${timestamp}`],
        [''],
        ['Metric', 'Value'],
        ['Total Applications', '156'],
        ['Approved', '128'],
        ['Pending', '20'],
        ['Rejected', '8'],
        [''],
        ['Financial Metric', 'Amount (₦)'],
        ['Total Disbursed', '2,450,000,000'],
        ['Recovery Rate', '87%'],
        ['Active Loans', '342'],
        [''],
        ['Region', 'Applications'],
        ['North Central', '45'],
        ['North East', '38'],
        ['North West', '52'],
        ['South East', '42'],
        ['South South', '48'],
        ['South West', '55'],
      ].map(row => row.join(',')).join('\n');

      // Create blob and download
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);

      link.setAttribute('href', url);
      link.setAttribute('download', `${fileName}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      showNotification(`${reportType} downloaded successfully as ${format}!`, 'success');
    }
  } catch (error) {
    console.error('Error generating report:', error);
    showNotification(`Error generating report: ${error}`, 'error');
  }
};

export const addNewRecord = (recordType: string) => {
  showNotification(`Opening form to add new ${recordType}. This will be replaced with a modal form.`, 'info');
  // Later: Open modal form
};

export const processAction = (actionType: string, data?: any) => {
  showNotification(`Processing ${actionType}... This will be replaced with actual API calls.`, 'info');
  // Later: API call to process action
};

export const scheduleAction = (actionType: string, date?: string) => {
  showNotification(`Scheduling ${actionType}${date ? ` for ${date}` : ''}... This will be replaced with calendar integration.`, 'info');
  // Later: Calendar integration
};

export const exportData = (dataType: string, format: string = 'Excel') => {
  showNotification(`Exporting ${dataType} data in ${format} format... This will be available for download shortly.`, 'info');
  // Later: API call to export data
};

export const sendNotification = (recipients: string[], message: string) => {
  showNotification(`Sending notification to ${recipients.length} recipients... This will be replaced with actual notification system.`, 'info');
  // Later: API call to send notifications
};

export const approveAction = (actionType: string, id: string) => {
  showNotification(`Approving ${actionType} (ID: ${id})... This will be replaced with actual approval workflow.`, 'success');
  // Later: API call to approve
};

export const rejectAction = (actionType: string, id: string) => {
  showNotification(`Rejecting ${actionType} (ID: ${id})... This will be replaced with actual rejection workflow.`, 'error');
  // Later: API call to reject
};

export const viewDetails = (itemType: string, id: string) => {
  showNotification(`Opening details for ${itemType} (ID: ${id})... This will be replaced with detailed view modal.`, 'info');
  // Later: Open detailed view modal
};

export const contactPerson = (name: string, phone: string, email: string) => {
  const contactInfo = `Contact: ${name}\nPhone: ${phone}\nEmail: ${email}`;
  showNotification(`Contact information:\n${contactInfo}`, 'info');
  // Later: Open contact modal or initiate call/email
};
